config/routes.rb
Rails.application.routes.draw do
  get 'nutrition/show'

  resources :users
  resources :sessions,      only: [:new, :create, :destroy]
  root 'static#index'
  get '/about' => 'static#about'
  get '/calories' => 'nutrition#index'
  post '/calories' => 'nutrition#show'
  get '/contacts' => 'static#contact'
  get '/info' => 'static#info'
  get '/missions' => 'static#missions'
  match 'login', :controller => :sessions, :to => :create, :via => :post
  match 'login', :controller => :sessions, :to => :new, :via => :get
  delete '/logout'  => 'sessions#destroy'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  validates :height, presence: true
  validates :weight, presence: true
  
  after_validation :log_errors, :if => Proc.new {|m| m.errors}

  def log_errors
    Rails.logger.debug self.errors.full_messages.join("\n")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    include SessionsHelper
  end

app/controllers/nutrition_controller.rb
class NutritionController < ApplicationController
  include HTTParty
  
  def show 
    input = params['search']
    search = input.downcase.tr(" ", "_")
    base_url = "https://api.nutritionix.com/v1_1/search/"+search+"?results=0:20&fields=item_name,brand_name,item_id,nf_calories&appId=8b2998ce&appKey=4122e31c0d2142192cb7068931a3d5ac"
    res = HTTParty.get(base_url)
    @nutr = JSON.parse(res.body)
    @searched = input
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to @user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
      log_out
      redirect_to root_url
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      flash[:error] = "There was a fatal error while saving"
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :height, :weight, :goal)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nutrition_helper.rb
module NutritionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/_footer.html.erb
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#home">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">About</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#services">Services</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Your Company 2014. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

app/views/layouts/_header.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
				<a img class="" src="assets/ipad.png" alt="">
                <a class="navbar-brand" href="/">
					<img style="max-width:150px; margin-top: -1em;" src="/assets/logo.png">
				</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
					<% if logged_in? %>
							<li><%= link_to "Missions", missions_path %></li>
							<li><%= link_to "Info", info_path %></li>
							<li><%= link_to "Search", calories_path %></li>
							<li class="dropdown">
								<%= link_to "Profile", current_user, :class => "dropdown-toggle", :data => {:toggle=>"dropdown"} %>
								<ul class="dropdown-menu" role="menu">
									<li><%= link_to "Update", edit_user_path(current_user)%></li>
							        <li><%= link_to "My Page", user_path(current_user) %></li>
							        <li class="divider"></li>
							        <li><%= link_to "Log out", logout_path, method: "delete" %></li>			         
									</ul>
								</li>
					<% else %>
                    	<li><%= link_to "About", about_path %></li>
                    	<li><%= link_to "Contacts", contacts_path%></li>
						<li><%= button_to "Login", login_path, method: "get", :class => "btn btn-default navbar-btn" %></li>
					<% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diet project</title>
  <script src="/assets/jquery.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="/assets/landing-page.css"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/messages' %>
	<%= render 'layouts/header' %>
	<div class="container">
	    <%= yield %>
	</div>
	  <%= render 'layouts/footer' %>
  </body>
</html>

app/views/nutrition/index.html.erb
<div id="calories">
	<div class="col-xs-10 col-sm-4 col-md-6">
		<h1>Search nutrition</h1>
		<%= form_tag("/calories", method: "post", class: "navbar-form navbar-left") do %>
  	  	<%= label_tag(:myform, "Search for:") %>
  		<%= text_field_tag(:search) %>
  		<%= submit_tag("Search", :class => "btn btn-success btn-small") %>
		<% end %> 
	</div>
</div>

app/views/nutrition/show.html.erb
<div id="calories">
<h3>Search Result for: <%= @searched %></h3>
<div class="bs-example">
<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Brand Name</th>
			<th>Servings</th>
			<th>Calories</th>
		</tr>
	</thead>
	<tbody>
 	   <% @nutr['hits'].each do |item| %>
	   <tr>
			<th><%= item['fields']['item_name'] %></th>
			<th><%= item['fields']['brand_name'] %></th>
			<th><%= item['fields']['nf_serving_size_qty'] %></th>
			<th><%= item['fields']['nf_calories'] %> calories</th>
	    </tr>
		<% end %>
	</tbody>
</table>
</div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
	  <%=@user.errors.full_messages%>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
	  <%=form_for(@user, :html => {:class => 'update'}) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name, :id => 'username'%>
      <%= f.label :email %>
      <%= f.text_field :email,:id => 'username' %>
      <%= f.label :password %>
      <%= f.password_field :password, :id => 'username' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, :id => 'username' %>
	  <%=f.label :height %>
	  <%=f.number_field :height, :id => "username" %> 
	  <%=f.label :weight %>
	  <%=f.number_field :weight, :id => "username" %>
	  <%=f.label :goal %>
	  <%=f.number_field :goal, :id => "username" %>
      <%=f.submit "Update my information", class: "btn btn-success btn-sm" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="col-xs-12 col-sm-12 col-md-12">
	<div class="row">
	        <div class="col-md-12">
	            <div class="pr-wrap">
	                <div class="pass-reset">
	                    <label>
	                        Enter the email you signed up with</label>
	                    <input type="email" placeholder="Email" />
	                    <input type="submit" value="Submit" class="pass-reset-submit btn btn-success btn-sm" />
	                </div>
	            </div>
	            <div class="wrap">
	                <p class="form-title"> Sign Up</p>
						<%=form_for(@user, :html => {:class => 'signup'}, :url => {:action => :create}) do |f| %>
						<%= render 'shared/error_messages' %>
						<%=f.label :username %>
						<%=f.text_field :name, :id => "username" %>
						<%=f.label :email %>
						<%=f.text_field :email, :id => "email"%>
						<%=f.label :password %>
						<%=f.password_field :password %>
						<%=f.label :password_confirmation %>
						<%=f.password_field :password_confirmation %>
						<%=f.label :height %>
						<%=f.number_field :height, :id => "username" %> 
						<%=f.label :weight %>
						<%=f.number_field :weight, :id => "username" %>
						<%=f.label :goal %>
						<%=f.number_field :goal, :id => "username" %>
						<%=f.submit "Create my account", class: "btn btn-success btn-sm" %>
					<% end %>
	            </div>
	        </div>
		</div>
	</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="col-xs-4 col-sm-4 col-md-4">
<%= image_tag "bodyimg.png", {height: 400}%>
</div>

<div class="col-xs-8 col-sm-8 col-md-8">
<h1>
  Welcome back, <%= @user.name %>.
</h1>
  Height: <%= @user.height %></br>
  Weight: <%= @user.weight %></br>
  <% if @user.weight < @user.goal %>
  	<%= @user.weight - @user.goal %> more to go!
  <% else %>
    You have reached your goal. Congratulations!
  <% end %>
  
  <% if @user.%>
</br>
  BMI: <%= Float(@user.weight / (@user.height)^2) %>
  <h6><a href="http://en.wikipedia.org/wiki/Body_mass_index">What is BMI?</a></h6>
</div>